apiVersion: v1
kind: Pod
metadata:
  name: terminal
spec:
  containers:
    - name: terminal
      image: helpyio/helpypro:latest
      command: ['sleep']
      args: ['infinity']
      envFrom:
       - configMapRef:
           name: env