apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-{{ .Values.image.name }}-svc
    labels:
        app: {{ .Release.Name }}-{{ .Values.image.name }}-svc
spec:
    type: {{ .Values.service.type }}
    selector:
        app: {{ .Release.Name }}-{{ .Values.image.name }}
    ports:
      - name: http 
        protocol: TCP
        port: 80
        targetPort: 80
        {{ if eq .Values.service.type "NodePort" }}
        nodePort: 30007
        {{ end }}