apiVersion: batch/v1
kind: Job
metadata:
  name: "helpy-setup"
spec:
  template:
    spec: 
      restartPolicy: Never
      containers:
        - name: helpypro
          imagePullPolicy: IfNotPresent
          image: helpyio/helpypro:latest
          command:
            - bundle
            - exec
            - rake
            - db:setup
          envFrom:
            - configMapRef:
                name: helpy-env