{{ if .Values.minio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      volumes:
      - name: minio-pv-claim
        persistentVolumeClaim:
          claimName: minio-pv-claim
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: minio-pv-claim
          mountPath: /usr/share/nginx/html
{{ end }}